# Generated by Django 5.2.3 on 2025-06-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bandeira', models.CharField(max_length=50)),
                ('imagem', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DUV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('data_viagem', models.DateField()),
                ('navio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duvs.navio')),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('passageiro', 'Passageiro'), ('tripulante', 'Tripulante')], max_length=20)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('foto', models.URLField()),
                ('sid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('duv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros', to='duvs.duv')),
            ],
        ),
    ]
