# Generated by Django 5.2.3 on 2025-06-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navio',
            name='imagem',
            field=models.ImageField(upload_to='navios/'),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='foto',
            field=models.ImageField(upload_to='passageiros/'),
        ),
    ]
